/*
 * File: leg_pos.c
 *
 * MATLAB Coder version            : 5.1
 * C/C++ source code generated on  : 06-Nov-2023 16:48:32
 */

/* Include Files */
#include "leg_pos.h"
#include "arm_math.h"

/* Function Declarations */
static float rt_atan2f_snf(float u0, float u1);

/* Function Definitions */
/*
 * Arguments    : float u0
 *                float u1
 * Return Type  : float
 */
static float rt_atan2f_snf(float u0, float u1)
{
  float y;
  if (u1 == 0.0F) {
    if (u0 > 0.0F) {
      y = PI / 2.0F;
    } else if (u0 < 0.0F) {
      y = -(PI / 2.0F);
    } else {
      y = 0.0F;
    }
  } else {
    y = atan2f(u0, u1);
  }

  return y;
}

/*
 * LEG_POS
 *     POS = LEG_POS(PHI1,PHI4)
 * Arguments    : float phi1
 *                float phi4
 *                float pos[2]
 * Return Type  : void
 */
void leg_pos(float phi1, float phi4, float pos[2])
{
  float a;
  float b_a;
  float t14;
  float t15;
  float t2;
  float t3;
  float t4;
  float t5;
  float t6;
  float t8_tmp;

  /*     This function was generated by the Symbolic Math Toolbox version 8.6. */
  /*     06-Nov-2023 16:46:59 */
  t2 = arm_cos_f32(phi1);
  t3 = arm_cos_f32(phi4);
  t4 = arm_sin_f32(phi1);
  t5 = arm_sin_f32(phi4);
  t6 = t2 / 20.0F;
  t8_tmp = t4 / 20.0F;
  t14 = t4 * 0.0105F;
  t15 = t5 * 0.0105F;
  t5 = t8_tmp + -(t5 / 20.0F);
  a = (t3 / 20.0F + -t6) + 0.06F;
  b_a = t14 + -t15;
  t4 = (t3 * 0.0105F + -(t2 * 0.0105F)) + 0.0126F;
  t5 = t5 * t5 + a * a;
  t4 = atanf(1.0F / (t4 + t5) * ((t15 + -t14) + sqrtf((b_a * b_a + t4 * t4) +
    -(t5 * t5)))) * 2.0F;
  t5 = t8_tmp + sinf(t4) * 0.105F;
  t4 = (t6 + arm_cos_f32(t4) * 0.105F) - 0.03F;
  pos[0] = sqrtf(t5 * t5 + t4 * t4); //L
  pos[1] = rt_atan2f_snf(t5, t4); // phi
}

/*
 * File trailer for leg_pos.c
 *
 * [EOF]
 */
