/*
 * File: lqr_k.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 27-Jan-2023 15:11:40
 */

/* Include Files */
#include "lqr_k.h"
#include <math.h>

/* Function Definitions */
/*
 * LQR_K
 *     K = LQR_K(L0)
 *
 * Arguments    : float L0
 *                float K[12]
 * Return Type  : void
 */
void lqr_k(float L0, float K[12])
{
  float t2;
  float t3;
  /*     This function was generated by the Symbolic Math Toolbox version 9.2.
   */
  /*     07-Feb-2023 16:51:43 */
  t2 = L0 * L0;
  t3 = L0 * L0 * L0;
  K[0] = ((L0 * -18.5950909F - t2 * 49.7698975F) + t3 * 77.1285553F) +
    0.236248106F;
  K[1] = ((L0 * 1.38104081F - t2 * 4.45693302F) + t3 * 5.44185114F) -
    0.0248529166F;
  K[2] = ((L0 * -2.47275281F - t2 * 13.4536648F) + t3 * 11.7544107F) +
    0.0411355756F;
  K[3] = ((L0 * 0.197767213F - t2 * 0.511617243F) + t3 * 0.588252664F) -
    1.81907E-5F;
  K[4] = ((L0 * -9.41135693F - t2 * 6.73949242F) + t3 * 25.4142818F) +
    0.182102561F;
  K[5] = ((L0 * 0.366148382F - t2 * 1.49042702F) + t3 * 1.92404306F) +
    0.0273396391F;
  K[6] = ((L0 * -7.85824347F - t2 * 7.99898434F) + t3 * 21.3454F) + 0.117749386F;
  K[7] = ((L0 * 0.428916F - t2 * 1.6714133F) + t3 * 2.23605561F) +
    0.00878415164F;
  K[8] = ((L0 * -63.7257271F + t2 * 247.677094F) - t3 * 366.508514F) +
    7.75056028F;
  K[9] = ((L0 * 6.85515261F - t2 * 31.1002674F) + t3 * 49.687851F) + 12.4316645F;
  K[10] = ((L0 * -2.1162622F + t2 * 8.27316475F) - t3 * 12.2959776F) +
    0.265644968F;
  K[11] = ((L0 * 0.207588255F - t2 * 0.936850071F) + t3 * 1.49383163F) +
    0.42507562F;
}

/*
 * File trailer for lqr_k.c
 *
 * [EOF]
 */
